import type { AppState } from "./types";

export const INITIAL_STATE: AppState = {
  metaFinal: 10_000_000,
  cuentas: [
    {
      id: "banres-principal",
      nombre: "Banreservas Principal",
      banco: "Banreservas",
      tipo: "operativa",
      balance: 8500,
      descripcion: "Cuenta operativa día a día",
    },
    {
      id: "banres-secundaria",
      nombre: "Banreservas Secundaria",
      banco: "Banreservas",
      tipo: "puente",
      balance: 3200,
      descripcion: "Cuenta puente para distribución",
    },
    {
      id: "qik-emergencia",
      nombre: "Qik – Fondo Emergencia",
      banco: "Qik",
      tipo: "meta",
      balance: 12000,
      meta: 100000,
      descripcion: "Meta inicial RD$100,000 → final RD$200,000",
    },
    {
      id: "qik-patrimonio",
      nombre: "Qik – Patrimonio",
      banco: "Qik",
      tipo: "meta",
      balance: 5000,
      meta: 10_000_000,
      descripcion: "Vehículo principal de construcción patrimonial",
    },
    {
      id: "qik-disfrute",
      nombre: "Qik – Disfrute",
      banco: "Qik",
      tipo: "meta",
      balance: 2000,
      descripcion: "Fondo de disfrute controlado",
    },
    {
      id: "qik-vehiculo",
      nombre: "Qik – Vehículo",
      banco: "Qik",
      tipo: "meta",
      balance: 4500,
      descripcion: "Cuotas y mantenimiento vehículo",
    },
    {
      id: "qik-inmueble",
      nombre: "Qik – Inmueble Futuro",
      banco: "Qik",
      tipo: "meta",
      balance: 0,
      descripcion: "Capital semilla para primer inmueble",
    },
    {
      id: "popular",
      nombre: "Popular",
      banco: "Banco Popular",
      tipo: "inversion",
      balance: 0,
      descripcion: "Cuenta inactiva – futura cuenta de inversión",
    },
  ],
  deudas: [
    {
      id: "vehiculo",
      nombre: "Préstamo Vehículo",
      balance: 980000,
      pagoMensual: 33494,
      tasa: 12,
      prioridad: "alta",
    },
    {
      id: "banres-card",
      nombre: "Tarjeta Banreservas Principal",
      balance: 85000,
      pagoMensual: 8500,
      prioridad: "alta",
    },
    {
      id: "combustible-card",
      nombre: "Tarjeta Combustible",
      balance: 12000,
      pagoMensual: 2000,
      prioridad: "media",
    },
  ],
  ingresos: [],
  logros: [
    {
      id: "l1",
      titulo: "Primer Escudo",
      descripcion: "Primeros RD$50,000 protegidos",
      umbral: 50000,
      tipo: "liquidez",
      completado: false,
    },
    {
      id: "l2",
      titulo: "Fondo Sólido",
      descripcion: "Primeros RD$100,000 protegidos",
      umbral: 100000,
      tipo: "liquidez",
      completado: false,
    },
    {
      id: "l3",
      titulo: "Tarjeta Controlada",
      descripcion: "Tarjeta principal bajo 50% de límite",
      umbral: 50,
      tipo: "deuda",
      completado: false,
    },
    {
      id: "l4",
      titulo: "Constructor Neto",
      descripcion: "Primeros RD$100,000 patrimoniales",
      umbral: 100000,
      tipo: "patrimonio",
      completado: false,
    },
    {
      id: "l5",
      titulo: "Cuarto de Millón",
      descripcion: "Primeros RD$250,000 netos",
      umbral: 250000,
      tipo: "patrimonio",
      completado: false,
    },
    {
      id: "l6",
      titulo: "Medio Millón",
      descripcion: "Primeros RD$500,000 netos",
      umbral: 500000,
      tipo: "patrimonio",
      completado: false,
    },
    {
      id: "l7",
      titulo: "El Primer Millón",
      descripcion: "RD$1,000,000 en patrimonio neto",
      umbral: 1_000_000,
      tipo: "patrimonio",
      completado: false,
    },
    {
      id: "l8",
      titulo: "Cinco Millones",
      descripcion: "RD$5,000,000 en patrimonio neto",
      umbral: 5_000_000,
      tipo: "patrimonio",
      completado: false,
    },
    {
      id: "l9",
      titulo: "Patrimonial",
      descripcion: "RD$10,000,000 – meta cumplida",
      umbral: 10_000_000,
      tipo: "patrimonio",
      completado: false,
    },
  ],
  recompensas: [
    { id: "r1", nombre: "Cena Sin Culpa", descripcion: "Una cena elegante, sin mirar el menú", nivel: 2, reclamada: false },
    { id: "r2", nombre: "Golf Weekend", descripcion: "Un fin de semana en el campo", nivel: 3, reclamada: false },
    { id: "r3", nombre: "Compra Personal", descripcion: "Una compra personal moderada sin justificación", nivel: 4, reclamada: false },
    { id: "r4", nombre: "Viaje Corto", descripcion: "Un viaje de 3-4 días sin presupuesto ajustado", nivel: 5, reclamada: false },
    { id: "r5", nombre: "Celebración Seria", descripcion: "Una celebración memorable por el primer millón", nivel: 7, reclamada: false },
  ],
  advisorMessages: [],
};

export const STORAGE_KEY = "wealthos-cesar-v1";
